name: CI

on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
  steps:
    -  uses: actions/checkout@17.0.1
    - name: Set up JDK 17
      uses: actions/setup-java@17.0.1
      with:
        distribution: "adopt"
        java-version: 17
    - name: clean build
      run: ./gradlew clean test --info --stacktrace